# Generated by Django 5.2 on 2025-05-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sumam limbu', max_length=300)),
                ('dob', models.CharField(default='2008/10/10', max_length=10)),
                ('citizenship', models.CharField(default='1234', max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8)),
                ('martial', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Married', max_length=20)),
                ('father', models.CharField(default='shyam rai', max_length=300)),
                ('education', models.CharField(choices=[('Master', 'Master'), ('Bachelor', 'Bachelor'), ('+2', '+2'), ('slc', 'slc')], default='Bachelor', max_length=10)),
                ('address', models.CharField(default='Itahari', max_length=50)),
                ('dependent', models.PositiveIntegerField(default=3)),
                ('employer', models.CharField(blank=True, default='rbbl', max_length=150, null=True)),
                ('position', models.CharField(blank=True, default='Assistant', max_length=150, null=True)),
                ('service_time', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('firm_name', models.CharField(blank=True, default='rbbl', max_length=150, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Medical', 'Medical'), ('Petroleum', 'Petroleum'), ('Retail', 'Retail'), ('Liquors & Drinks', 'Liquors & Drinks'), ('Hardware', 'Hardware')], default='Agriculture', max_length=150, null=True)),
                ('pan_no', models.PositiveIntegerField(blank=True, default='12345', null=True)),
                ('firm_address', models.CharField(blank=True, default='Itahari-20', max_length=150, null=True)),
                ('salary', models.FloatField(default=0.0)),
                ('business_income', models.FloatField(default=0.0)),
                ('agriculture', models.FloatField(default=0.0)),
                ('house_rent', models.FloatField(default=0.0)),
                ('family_income', models.FloatField(default=0.0)),
                ('other_income', models.FloatField(default=0.0)),
                ('loan_amount', models.PositiveIntegerField()),
                ('tenure', models.PositiveIntegerField(default=10)),
                ('interest', models.FloatField(default=10.12)),
                ('loan_type', models.CharField(default='Home', max_length=50)),
                ('plot_no', models.CharField(default='5684', max_length=50)),
                ('plot_area', models.CharField(default='0-0-10-0', max_length=50)),
                ('plot_address', models.CharField(blank=True, default='Itahari-20', max_length=200, null=True)),
                ('plot_owner', models.CharField(default='Roshan Rai', max_length=150)),
                ('plot_value', models.FloatField(default=4632450)),
                ('home_value', models.FloatField(default=0.0)),
                ('plot_market_value', models.FloatField(blank=True, default=200000, null=True)),
                ('land_value', models.PositiveIntegerField(default=0)),
                ('buildingvalue', models.PositiveIntegerField(default=0)),
                ('family_property', models.PositiveIntegerField(default=0)),
                ('vehicle', models.FloatField(default=0.0)),
                ('collateral_place', models.CharField(choices=[('Main Business Area', 'Main Business Area'), ('Simple Business Area', 'Simple Business Area'), ('Dense/Main Residential Area', 'Dense/Main Residential Area'), ('Simple Residential Area', 'Simple Residential Area'), ('Other Area', 'Other Area')], default='Main Business Area', max_length=60)),
                ('income_tenure', models.CharField(choices=[('upto loan tenure permanent income', 'Upto loan tenure permanent income'), ('upto near loan tenure permanent income', 'Upto near loan tenure permanent income'), ('upto half of the loan tenure', 'Upto half of the loan tenure'), ('probability of upto half of the loan tenure', 'Probability of upto half of the loan tenure'), ('other', 'Other')], default='upto loan tenure permanent income', max_length=200)),
                ('client_distance', models.CharField(choices=[('Less than 2km', 'Less than 2km'), ('2km to 5km', '2km to 5km'), ('5km to 10km', '5km to 10km'), ('10km to 15km', '10km to 15km'), ('More than 15km', 'More than 15km')], default='Less than 2km', max_length=200)),
                ('banking_history', models.CharField(choices=[('payment after full rebate', 'Payment after full rebate'), ('payment after 50 percent rebate', 'Payment after 50 percent rebate'), ('no banking transactions', 'No banking transactions'), ('payment period less than 3 months', 'Payment period less than 3 months'), ('payment period more than 3 months', 'Payment period more than 3 months'), ('payment period more than 6 months', 'Payment period more than 6 months')], default='payment after full rebate', max_length=100, null=True)),
                ('banking_year', models.CharField(choices=[('more than 5 years', 'More than 5 years'), ('(4-5)years', '(4-5) years'), ('(3-4)years', '(3-4) years'), ('(1-3)years', '(1-3) years'), ('less than 1 year', 'Less than 1 year')], default='more than 5 years', max_length=100)),
                ('loan_committee', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Simple', 'Simple'), ('Weak', 'Weak'), ('Risky', 'Risky')], default='Excellent', max_length=20)),
                ('loan_status', models.CharField(blank=True, default='preview', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20, unique=True)),
                ('disbursement_date', models.DateField()),
                ('disbursement_status', models.CharField(choices=[('Disbursed', 'Disbursed'), ('Not Disbursed', 'Not Disbursed')], default='Not Disbursed', max_length=15)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='homeloanapp.clientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_date', models.DateField(blank=True, null=True)),
                ('settle_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='homeloanapp.clientdetails')),
            ],
        ),
    ]
